- name: Include variables from kafka role
  include_vars:
    file: ../vars/all.yml

- name: Start Kafka Controller
  debug:
    msg: "Starting Kafka Controller..."

- name: Execute command to start Kafka Controller
  shell: "nohup {{ kafka_path }}/bin/kafka-server-start {{ kafka_path }}/etc/kafka/kraft/controller.properties > /dev/null 2>&1 & echo $!"
  register: kafka_controller_pid
  async: 300
  poll: 0

- name: Wait for Kafka Controller to start
  ansible.builtin.wait_for:
    timeout: 30  # Adjust timeout as needed
    host: 0.0.0.0
    port: 19093  # Replace with the appropriate port where Kafka should be available
    state: started
  delegate_to: localhost
  register: kafka_controller

#- name: Debug Kafka started status
#  debug:
#    var: kafka_started

- name: Display success message if Kafka process is running
  debug:
    msg: "Kafka Controller is running."
  when: kafka_controller.state == 'started'

- name: Start Kafka Broker 
  debug:
    msg: "Starting Kafka Broker..."

- name: Execute command to start Kafka Broker
  shell: "nohup {{ kafka_path }}/bin/kafka-server-start {{ kafka_path }}/etc/kafka/kraft/broker.properties"
  register: kafka_broker_pid
  async: 300
  poll: 0  

- name: Wait for Kafka Broker to start
  ansible.builtin.wait_for:
    timeout: 30  # Adjust timeout as needed
    host: 0.0.0.0
    port: 9092  # Replace with the appropriate port where Kafka should be available
    state: started
  delegate_to: localhost
  register: kafka_broker



- name: Debug Kafka started status
  debug:
    var: kafka_broker_pid



- name: Debug Kafka started status
  debug:
    var: kafka_broker

- name: Display success message Kafka Broker is started
  debug:
    msg: |
      Kafka Broker is started.
      The playbook completed successfully.
  when: kafka_broker.state == 'started'
