- name: Include variables from kafka role
  include_vars:
    file: ../vars/all.yml

- name: Stop Kafka Broker 
  debug:
    msg: "Stopping Kafka Broker..."

- name: Execute command to stop Kafka Broker
  shell: "nohup {{ kafka_path }}/bin/kafka-server-stop {{ kafka_path }}/etc/kafka/kraft/broker.properties  > /dev/null 2>&1 &"
  
- name: Display success message Kafka Broker is stopped
  debug:
    msg: |
      Kafka Broker is stoped.
      The task completed successfully.
