- name: Start Padas UI service
  debug:
    msg: "Starting Padas UI service..."

- name: Include variables from padas-ui role
  include_vars:
    file: ../vars/all.yml

- name: Execute command to start Padas UI service    
  command: "{{ padas_ui_path }}/bin/padas-ui start"

- name: Wait for Padas UI process to start
  ansible.builtin.shell: "ps aux | grep {{ ps_padas_ui }}"
  register: padas_ui_status
  retries: 3
  delay: 10
  until: padas_ui_status.stdout.find(ps_padas_ui) != -1

- name: Display success message Padas UI is started
  debug:
    msg: |
      Padas UI is started.
      The task completed successfully.
