- name: Start Padas Engine service
  debug:
    msg: "Starting Padas Engine service..."

- name: Include variables from padas-engine role
  include_vars:
    file: ../vars/all.yml
 
- name: Execute command to start Padas Engine service
  command: "{{ padas_engine_path }}/bin/padas start"

- name: Wait for Padas Engine process to start
  ansible.builtin.shell: "jps -m | grep {{ jps_padas }}"
  register: padas_engine_status
  retries: 3
  delay: 10
  until: padas_engine_status.stdout.find(jps_padas) != -1

- name: Display success message Padas Engine is started
  debug:
    msg: |
      Padas Engine is started.
      The task completed successfully.


