- name: Start Services
  import_playbook: start-services.yml

- name: Quick Start
  hosts: localhost
  tasks:
    # Authenticate to Padas Engine
    - name: Get tokens for Padas Engine
      include_tasks: ../roles/padas-engine/tasks/get_tokens.yml
    # Create the topics required by the quick start
    - name: Create Topics
      include_tasks: ../roles/padas-engine/tasks/create_topics.yml
    # Bulk Create the tasks required by the quick start
    - name: Bulk Create Rules
      include_tasks: ../roles/padas-engine/tasks/create_rules_bulk.yml
    # Bulk Create the tasks required by the quick start
    - name: Bulk Create Tasks
      include_tasks: ../roles/padas-engine/tasks/create_tasks_bulk.yml
    # Create the pipelines required by the quick start
    - name: Bulk Create Pipeline
      include_tasks: ../roles/padas-engine/tasks/create_pipeline_bulk.yml
    # Create the topologies required by the quick start
    - name: Bulk Create Topologies
      include_tasks: ../roles/padas-engine/tasks/create_topologies_bulk.yml
    # Restart Padas Engine for enabling topologies
    - name: Stop Padas Engine
      include_tasks: ../roles/padas-engine/tasks/stop.yml
    - name: Start Padas Engine
      include_tasks: ../roles/padas-engine/tasks/start.yml

- name: Wait for Padas Engine to start
  hosts: localhost
  tasks:
    - name: Wait for 10 seconds for Padas Engine to start
      pause:
        seconds: 10