- name: Start Kafka Controller 
  hosts: kafka-controller
  tasks:
    - name: Include start task for Kafka Controller
      include_role:
        name: roles/kafka
        tasks_from: start-controller.yml

- name: Start Kafka Broker 
  hosts: kafka-broker
  tasks:
    - name: Include start task for Kafka Broker
      include_role:
        name: roles/kafka
        tasks_from: start-broker.yml

- name: Start Padas Engine services
  hosts: padas-engine
  tasks:
    - name: Include start tasks for Padas Engine
      include_role:
        name: roles/padas-engine
        tasks_from: start.yml

- name: Start Padas UI services
  hosts: padas-ui
  tasks:
    - name: Include start tasks for Padas UI
      include_role:
        name: roles/padas-ui
        tasks_from: start.yml

- name: Wait for services to start
  hosts: localhost
  tasks:
    - name: Pause for 30 seconds
      pause:
        seconds: 30